esphome:
  name: esp32_test
  platform: ESP32
  board: esp32dev

# Habilita logging para ver mensajes en la consola
logger:

# Habilita OTA para actualizar firmware sin USB
ota:

# Solo modo AP para configurar WiFi si es necesario
wifi:
  ap:
    ssid: "ESP32_Config"
    password: "12345678"

# LED conectado a un pin seguro (GPIO5)
output:
  - platform: gpio
    pin: 5
    id: led_test

light:
  - platform: binary
    name: "LED Test"
    output: led_test

# Intervalo de parpadeo del LED
interval:
  - interval: 1s
    then:
      - light.toggle: led_test
      - logger.log: "LED toggled!"
