esphome:
  name: !secret device_name
  friendly_name: !secret device_friendly_name

esp32:
  board: esp32dev
  framework:
    type: arduino
    version: recommended

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Hotspot de respaldo cuando no hay conexión
  ap:
    ssid: !secret fallback_ap_ssid
    password: !secret fallback_ap_password

mqtt:
  broker: !secret mqtt_broker_ip
  port: !secret mqtt_port
  topic_prefix: dht_mqtt
  discovery: true
  discovery_prefix: homeassistant

# Sensor DHT11
sensor:
  - platform: dht
    pin: GPIO13
    model: DHT11
    temperature:
      name: "Temperatura DHT11"
      id: dht_temp
      accuracy_decimals: 1
    humidity:
      name: "Humedad DHT11"
      id: dht_hum
      accuracy_decimals: 1
    update_interval: 10s

captive_portal: